### ISSUE TITLE
Unable to load data

### ISSUE THREAD

**Issue by shweta-garg** [dheeraj7596/META#1]
![image](https://user-images.githubusercontent.com/16982414/110589982-c8187900-813c-11eb-8a4c-1a3572ef9152.png)
Once the data has been loaded into df in the util\write_to_file.py then it is not able to perform any operations on the df. I tried printing the df.columns even that throws error. Am I doing something wrong?

**Comment by dheeraj7596** [comment]
Can you make sure the pandas version is 1.1.0?

**Comment by shweta-garg** [comment]
I tried with that, it does not help. I am still getting the same issue.

**Comment by dheeraj7596** [comment]
Is the pickle version 4.0?

**Comment by shweta-garg** [comment]
Yes. I have also rechecked all the versions of the packages you have listed on the README. It is still throwing me this error.

**Comment by dheeraj7596** [comment]
Interesting, because I just tested on my end and it's working fine. I think this error is mostly due to pickle and pandas version. The pickle version should be 4.0 and pandas 1.1.0.

**Comment by shweta-garg** [comment]
I was finally able to load the data after making sure each and every package matched the version you wanted. But now when I am running the code for the dblp dataset that you have provided in your Github repo. I am getting the following error. I have not changed anything just running it simply. Could you help me out in this?

![image](https://user-images.githubusercontent.com/16982414/111730494-8aec6f00-883f-11eb-8b85-cd2c6d06c6de.png)

**Comment by dheeraj7596** [comment]
I will check this and will get back to you.

**Comment by shweta-garg** [comment]
Did you get a chance to look at this?

**Comment by dheeraj7596** [comment]
Updated the code and requirements in the README. Please try once with the updated code.
